services:
  django-backend:
    container_name: django-container
    build: ./migrant-info-platform/backend
    ports:
      - "8000:8000"
    volumes:
      - ./migrant-info-platform/backend:/app
    environment:
      - DEBUG=True
    
  react-frontend:
    container_name: react-container
    build: 
      context: ./migrant-info-platform/frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./migrant-info-platform/frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development

volumes:
  node_modules: