name: chatbot_service
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # Core GPU Libraries
  - cudatoolkit=11.8
  - pytorch=2.5.1         # GPU‑enabled PyTorch build
  - pytorch-cuda=11.8     # matches cudatoolkit
  - torchvision=0.20.1    # matching CUDA build
  - torchaudio=2.5.1      # matching CUDA build
  - faiss-gpu=1.9.0       # GPU FAISS with ABI for PyTorch

  # Pin NumPy to 1.x to maintain ABI compatibility
  - numpy=1.24.3

  # Other Conda dependencies
  - packaging

  # Pip‑only packages
  - pip:
      - numpy<2               # prevents NumPy 2.x ABI break
      - transformers==4.51.3
      - accelerate==1.6.0
      - sentence-transformers==4.1.0
      - fastapi==0.115.12
      - uvicorn[standard]==0.34.2
      - spacy==3.8.5
      - beautifulsoup4==4.12.2
      - ipynbname>=2024.1.0
      - python-dotenv==1.1.0
