# Generated by Django 5.1.3 on 2025-04-25 08:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='faq_title',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.TextField(max_length=255),
        ),
    ]
