# Generated by Django 5.1.3 on 2025-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_faqcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order'], 'verbose_name': 'FAQ Category', 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='faq_title',
            field=models.TextField(max_length=100),
        ),
    ]
