# Generated by Django 5.1.3 on 2025-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_faqcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='faq_title',
            field=models.CharField(max_length=100),
        ),
    ]
