# Generated by Django 5.1.3 on 2025-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_faqcategory_faq_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order'], 'verbose_name': 'FAQ Category', 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
